### PR TITLE
Update server runner

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
Fixed the updated `isServerStopped` method name and moved the file into different folder, so it is now parseable by Android Studio

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
Why this file is not visible in the Studio then?

**Comment by mykola-mokhnach** [comment]
so it does not detect the compilation error?

**Comment by mykola-mokhnach** [comment]
This file was actually broken after we renamed `isStopServer` property in https://github.com/appium/appium-uiautomator2-server/pull/140/files

**Comment by mykola-mokhnach** [comment]
I've moved it under different folder, thus package name stays the same. @vmaxim Would it be ok?

**Comment by vmaxim** [comment]
My fault - refactoring does not affects all builds variants in studio :(
